config/routes.rb
Blog::Application.routes.draw do
  resources :contacts

  resources :articles

  resources :contents

  resources :medias

  resources :maps

  resources :posts do
    resources :comments
  end

  root :to => "home#index"

end

app/models/media.rb
class Media < ActiveRecord::Base
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
  # GET /medias
  # GET /medias.xml

  def index
    @medias = Media.all

    @medias.each do |media|
     media[:extension]=media.file.split('.')[1]
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @medias }
    end
  end

  # GET /medias/1
  # GET /medias/1.xml
  def show
    @media = Media.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.iphone # show.iphone.erb
      format.xml  { render :xml => @media }
    end
  end

  # GET /medias/new
  # GET /medias/new.xml
  def new
    @media = Media.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @media }
    end
  end

  # GET /medias/1/edit
  def edit
    @media = Media.find(params[:id])
  end

  # POST /medias
  # POST /medias.xml
  def create
    @media = Media.new(params[:media])

    respond_to do |format|
      if @media.save
        format.html { redirect_to(@media, :notice => 'Media was successfully created.') }
        format.xml  { render :xml => @media, :status => :created, :location => @media }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @media.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /medias/1
  # PUT /medias/1.xml
  def update
    @media = Media.find(params[:id])

    respond_to do |format|
      if @media.update_attributes(params[:media])
        format.html { redirect_to(@media, :notice => 'Media was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @media.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /medias/1
  # DELETE /medias/1.xml
  def destroy
    @media = Media.find(params[:id])
    @media.destroy

    respond_to do |format|
      format.html { redirect_to(medias_url) }
      format.xml  { head :ok }
    end
  end

 def list
    @medias = Media.all

    @medias.each do |media|
     media[:extension]=media.file.split('.')[1]
    end
  end

end

app/helpers/medias_helper.rb
module MediasHelper
end

app/views/medias/_form.html.erb
<%= form_for(@media) do |f| %>
  <% if @media.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@media.errors.count, "error") %> prohibited this media from being saved:</h2>

      <ul>
      <% @media.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medias/_index.iphone.erb
<body class="list">
  <div id="topbar">
    <div id="title">Medias</div>
    <div id="leftnav">
      <%= link_to image_tag("iphone_nav/home.png", :alt => "Accueil"), :controller =>"home" %>

    </div>
  </div>
  <div id="content">
    <ul>
      <li class="title">Images</li>
    <% @medias.each do |media| %>


      <li class="withimage">
      <% if media[:extension]=="jpg" %>
        <%= link_to(media) do %>
          <%=  image_tag(["thumbs/",media.file].join(''), :alt => media.name)%>
          <span class="name"><%= media.name %></span>
          <span class="arrow"></span>
        <% end %>
      <% elsif media[:extension]=="mp4" %>
        <%= link_to(["images/",media.file].join('')) do %>
          <%=  image_tag(["thumbs/",media.file].join(''), :alt => media.name)%>
          <span class="name"><%= media.name %></span>
          <span class="arrow"></span>
        <% end %>
      <% elsif media[:extension]=="swf" %>
          <%= link_to(media) do %>
          <%=  image_tag(["thumbs/",media.file].join(''), :alt => media.name)%>
          <span class="name"><%= media.name %></span>
          <span class="arrow"></span>
        <% end %>
      <% end %>
      </li>
    <% end %>
      <li class="title">Animation</li>
      <li class="title">Vidéo</li>
    </ul>
  </div>
</body>

app/views/medias/_menu.html.erb
<h3>Liste des médias</h3>

 <script type="text/javascript">
		$(document).ready(function() {
			/*
			*   Examples - images
			*/
<% for media in list_medias %>


	<% if media[:extension]=="jpg" %>
		$("<%=  ["a#media",media.id].join('')%>").fancybox({
				'titleShow'		: false,
				'transitionIn'	: 'elastic',
				'transitionOut'	: 'elastic'
			});
	<% elsif media[:extension]=="swf" %>
		$("<%=  ["a#media",media.id].join('')%>").fancybox({
				'padding'			: 0,
				'autoScale'			: false,
				'transitionIn'		: 'none',
				'transitionOut'		: 'none'
			});
	<% else %>
		<%= "probleme" %>
	<% end %>

<% end %>
			
		});
	</script>


	
<% for media in list_medias %>
  <div>

	<% if media[:extension]=="jpg" %>
		<%= link_to image_tag(media.file, :alt => media.name, :width => "200", :height => "100"), ["http://localhost:3000/images/",media.file].join(''), :id => ["media",media.id].join('') %>
	<% elsif media[:extension]=="swf" %>
		<a href="swfs/<%= media.file %>" id="<%= ["media",media.id].join('') %>" >Swf</a>
	<% else %>
		<%= "probleme" %>
	<% end %>

  </div>
<% end %>

app/views/medias/edit.html.erb
<h1>Editing media</h1>

<%= render 'form' %>

<%= link_to 'Show', @media %> |
<%= link_to 'Back', medias_path %>

app/views/medias/index.html.erb
<h1>Liste des médias</h1>


<% @medias.each do |media| %>
  <div>
   <strong><%= media.name %></strong><br />
    Fichier : <%= media.file %><br />
    Type de média : <%= media.type %><br />
    Extension : <%= media[:extension] %><br />
	<% if media[:extension]=="jpg" %>
		a<%= link_to image_tag(media.file, :alt => media.name, :width => "200", :height => "100"), ["http://localhost:3000/images/",media.file].join(''), :class =>"thickbox" %>
	<% elsif media[:extension]=="swf" %>
		b<%= link_to image_tag(media.file, :alt => media.name, :width => "200", :height => "100"), media, :class =>"thickbox" %>
	<% else %>
		<%= "probleme" %>
	<% end %>
	<!--<ul>
		<li><%= link_to 'Voir le média', media %></li>
		<li><%= link_to 'Editer', edit_media_path(media) %></li>
		<li><%= link_to 'Supprimer', media, :confirm => 'Êtes vous certain de vouloir supprimer ce media?', :method => :delete %></li>
	</ul>-->
  </div>
<% end %>

<!--
<%= link_to 'Ajouter un Média', new_media_path %>
-->

app/views/medias/index.iphone.erb
<body class="list">
  <div id="topbar">
    <div id="title">Medias</div>
    <div id="leftnav">
      <%= link_to image_tag("iphone_nav/home.png", :alt => "Accueil"), :controller =>"home" %>

    </div>
  </div>
  <div id="content">
    <ul>
      <li class="title">Images</li>
    <% @medias.each do |media| %>


      <li class="withimage">
      <% if media[:extension]=="jpg" %>
        <%= link_to(media) do %>
          <%=  image_tag(["thumbs/",media.file].join(''), :alt => media.name)%>
          <span class="name"><%= media.name %></span>
          <span class="arrow"></span>
        <% end %>
      <% elsif media[:extension]=="mp4" %>
        <%= link_to(["images/",media.file].join('')) do %>
          <%=  image_tag(["thumbs/",media.file].join(''), :alt => media.name)%>
          <span class="name"><%= media.name %></span>
          <span class="arrow"></span>
        <% end %>
      <% elsif media[:extension]=="swf" %>
          <%= link_to(media) do %>
          <%=  image_tag(["thumbs/",media.file].join(''), :alt => media.name)%>
          <span class="name"><%= media.name %></span>
          <span class="arrow"></span>
        <% end %>
      <% end %>
      </li>
    <% end %>
      <li class="title">Animation</li>
      <li class="title">Vidéo</li>
    </ul>
  </div>
</body>

app/views/medias/new.html.erb
<h1>New media</h1>

<%= render 'form' %>

<%= link_to 'Back', medias_path %>

app/views/medias/show.html.erb
<p id="notice"><%= notice %></p>


<% if @extension=="jpg" %>
	<%= "image" %>
<% elsif @extension="swf" %>
	<%= "animation" %>
<% else %>
	<%= "probleme" %>
<% end %>
<p>
  <b>Name:</b>
  <%= @media.name %>
</p>

<p>
  <b>File:</b>
  <%= @media.file %>
</p>

<p>
  <b>Type:</b>
  <%= @media.type %>
</p>
<%= swf_object("/swfs/360_1.swf", "flash_id", "550", "400", "9", "#000000",
        {:wmode => "transparent", :quality => "high"},
        {:myvar1 => "foo1", :myvar2 => "foo2"},
        true) %>-->
<div id='flash_id' align='center'>This website requires <a href='http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash&promoid=BIOW' target='_blank'>Flash player</a> 9 or higher.</div><script type='text/javascript'>var so = new SWFObject('/swfs/360_1.swf', 'flash_id', '550', '400', '9', '#000000');so.addParam('wmode', 'transparent');so.addParam('quality', 'high');so.addVariable('myvar1', 'foo1');so.addVariable('myvar2', 'foo2');so.write('flash_id');</script>
<!--
<%= link_to 'Edit', edit_media_path(@media) %> |
<%= link_to 'Back', medias_path %>-->

app/views/medias/show.iphone.erb
<body>
  <div id="topbar">
    <div id="title"><%= @media.name %></div>
    <div id="leftnav">
      <%= link_to image_tag("iphone_nav/home.png", :alt => "Accueil"), :controller =>"home" %>
      <%= link_to "Medias", :controller => "medias" %>
    </div>
  </div>
  <div id="content">
    <%=  image_tag(@media.file, :alt => @media.name)%>
    
  </div>
</body>